### ISSUE TITLE
No signature of method: geb.navigator.NonEmptyNavigator.moduleList() is applicable for argument types: (java.lang

### ISSUE THREAD

**Issue by geb-bot** [geb/issues#209]
Originally created by Nikol Marku.

Hi, 

I am trying to use Geb modules as described on the book of Geb '0.7.0' section 6.3 Using modules for repeating content on a page 
When I try to run the test on our web site I get the error: 

Error No signature of method: geb.navigator.NonEmptyNavigator.moduleList() is applicable for argument types: (java.lang.Class, geb.navigator.NonEmptyNavigator) values: [class com.creditpal.web.functional.spec.TestModule, [[[[[FirefoxDriver: firefox on XP (a1acef54-0b23-4086-84b7-0f40a2308edc)] -> tag name: html]] -> css selector: table tr], [[[[FirefoxDriver: firefox on XP (a1acef54-0b23-4086-84b7-0f40a2308edc)] -> tag name: html]] -> css selector: table tr], [[[[FirefoxDriver: firefox on XP (a1acef54-0b23-4086-84b7-0f40a2308edc)] -> tag name: html]] -> css selector: table tr]]] 

groovy.lang.MissingMethodException: No signature of method: geb.navigator.NonEmptyNavigator.moduleList() is applicable for argument types: (java.lang.Class, geb.navigator.NonEmptyNavigator) values: [class com.creditpal.web.functional.spec.TestModule, [[[[[FirefoxDriver: firefox on XP (a1acef54-0b23-4086-84b7-0f40a2308edc)] -> tag name: html]] -> css selector: table tr], [[[[FirefoxDriver: firefox on XP (a1acef54-0b23-4086-84b7-0f40a2308edc)] -> tag name: html]] -> css selector: table tr], [[[[FirefoxDriver: firefox on XP (a1acef54-0b23-4086-84b7-0f40a2308edc)] -> tag name: html]] -> css selector: table tr]]] 
        at geb.navigator.NonEmptyNavigator.methodMissing(NonEmptyNavigator.groovy:350) 
        at geb.content.NavigableSupport.methodMissing(NavigableSupport.groovy:121) 
        at geb.Page.methodMissing(Page.groovy) 
        at geb.content.PageContentTemplateFactoryDelegate.methodMissing(PageContentTemplateFactoryDelegate.groovy:33) 
        at geb.content.PageContentTemplateFactoryDelegate.invokeMethod(PageContentTemplateFactoryDelegate.groovy) 
        at com.creditpal.web.functional.spec.TestPage._clinit__closure2_closure3(TestPage.groovy:17) 
        at com.creditpal.web.functional.spec.TestPage._clinit__closure2_closure3(TestPage.groovy) 
        at geb.content.PageContentTemplate.invokeFactory(PageContentTemplate.groovy:134) 
        at geb.content.PageContentTemplate.create_closure1(PageContentTemplate.groovy:103) 
        at geb.content.PageContentTemplate.create_closure1(PageContentTemplate.groovy) 
        at geb.content.PageContentTemplate.create(PageContentTemplate.groovy:119) 
        at geb.content.PageContentTemplate.get(PageContentTemplate.groovy:98) 
        at geb.content.NavigableSupport.getContent(NavigableSupport.groovy:43) 
        at geb.content.NavigableSupport.propertyMissing(NavigableSupport.groovy:127) 
        at geb.Page.propertyMissing(Page.groovy) 
        at com.creditpal.web.functional.spec.TestPage.simpleTest(TestPage.groovy:21) 
        at com.creditpal.web.functional.spec.TestPage._clinit__closure1(TestPage.groovy:12) 
        at com.creditpal.web.functional.spec.TestPage._clinit__closure1(TestPage.groovy) 
        at geb.Page.verifyAt(Page.groovy:123) 
        at geb.Browser.at(Browser.groovy:260) 
        at geb.spock.GebSpec.methodMissing(GebSpec.groovy:51) 
        at com.creditpal.web.functional.spec.TestModuleSpec.Go To reports(TestModuleSpec.groovy:21) 

I have tried to use the code from the manual and run it on the sample html as described on section 6.3 using modules and I get the same error as well. 

Any idea why ? 

here is the code from the Manual: 
6.3 Using modules for repeating content on a page 

Other than content that is repeated on different pages (like the shopping cart mentioned above), pages also have content that is repeated on the page itself. On a checkout page, the contents of the shopping cart could be summarized with the product name, the quantity and price for each product contained. For this kind of page, a list of modules can be collected using the moduleList function. 

Consider the following HTML for our cart contents: 

Product Quantity    Price
The Book Of Geb 1   5.99
Geb Single-User License 1   99.99
Geb Multi-User License  1   199.99

We can model one line of the table like this: 

class CartRow extends Module { 
    static content = { 
        cell { $("td", it) } 
        productName { cell(0).text() } 
        quantity { cell(1).text().toInteger() } 
        price { cell(2).text().toDouble() } 
    } 
} 

And define a list of CartRows in our Page: 

class CheckoutPage extends Page { 
    static content = { 
        cartItems { moduleList CartRow, $("table tr").tail() } // tailing to skip the header row 
    } 
} 
## 

geb and spock version : org.codehaus.geb:             geb-spock:0.6.1 

selenium version:         2.23.1 
groovy:                            1.7.10 
## grails :                              1.3.7 

N.Marku

**Comment by dhillsberry** [comment]
class FiddleExampleRow extends Module {
    static content = {
        cell { $("td", it) }
        item1 { cell(0).text() }
        item2 { cell(1).text() }
    }
}

**Comment by dhillsberry** [comment]
I have been experiencing the same problem.
The problem can be recreated using the project at 
     https://github.com/geb/geb-example-maven 
with the following test code

```groovy
class FiddleExampleRow extends Module {
    static content = {
        cell { $("td", it) }
        item1 { cell(0).text() }
        item2 { cell(1).text() }
    }
}


class FiddleExamplePage extends Page {
    static url = 'http://output.jsbin.com/ruqaxejoyi'
    static at = { title == "JS Bin" }

    static content = {
        tableRows { moduleList FiddleExampleRow, $("table tr")  }
    }
}


class FiddleExampleSpec extends GebSpec {

    def "can get to the Fiddle Example"() {
        when:
        to FiddleExamplePage

        then:
        assert tableRows[1].item2 == "Cell1.2"

    }
}
```

This project returns...
``Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.406 sec <<< FAILURE! - in FiddleExampleSpec
can get to the Fiddle Example(FiddleExampleSpec)  Time elapsed: 3.378 sec  <<< ERROR!
groovy.lang.MissingMethodException: 
No signature of method: geb.content.PageContentTemplateFactoryDelegate.moduleList() is applicable for argument types: (java.lang.Class, geb.navigator.NonEmptyNavigator) values: [class FiddleExampleRow, [[[ChromeDriver: chrome on MAC (85281a9ffcd4ca8c38b88177aeec274a)] -> css selector: table tr], [[ChromeDriver: chrome on MAC (85281a9ffcd4ca8c38b88177aeec274a)] -> css selector: table tr], [[ChromeDriver: chrome on MAC (85281a9ffcd4ca8c38b88177aeec274a)] -> css selector: table tr], [[ChromeDriver: chrome on MAC (85281a9ffcd4ca8c38b88177aeec274a)] -> css selector: table tr]]]
Possible solutions: moduleList(java.lang.Class, geb.navigator.Navigator), moduleList(java.lang.Class, geb.navigator.Navigator, java.lang.Object), moduleList(java.util.Map, java.lang.Class, geb.navigator.Navigator), moduleList(java.util.Map, java.lang.Class, geb.navigator.Navigator, java.lang.Object), module(java.lang.Class), module(java.lang.Class, java.lang.Object)
	at FiddleExampleSpec.can get to the Fiddle Example(FiddleExampleSpec.groovy:13)
``

**Comment by erdi** [comment]
`moduleList()` api has changed, see the appropriate section of the manual at http://gebish.org/manual/current/#repeating-content for detals
