### ISSUE TITLE
consolegroovy run the sample "manual 0.10.0 - 1.4.2 Scripting with Page Objects" but does not recognizes  page'DSL

### ISSUE THREAD

**Issue by pepllubc** [geb/issues#375]
//consolegroovy 2.4.3  .. Eclipse gives me the same result
groovy> @Grapes([ 
groovy>     @Grab("org.gebish:geb-core:0.10.0"), 
groovy>     @Grab("org.seleniumhq.selenium:selenium-firefox-driver:2.45.0"), 
groovy>     @Grab("org.seleniumhq.selenium:selenium-support:2.45.0") 
groovy> ]) 
groovy> import geb.Browser 
groovy> import geb.Page 
groovy> import geb.Module 
groovy>   
groovy> // modules are reusable fragments that can be used across pages that can be parameterised 
groovy> // here we are using a module to model the search function on the home and results pages 
groovy> class GoogleSearchModule extends Module { 
groovy>   
groovy>     // a parameterised value set when the module is included 
groovy>     def buttonValue 
groovy>   
groovy>     // the content DSL 
groovy>     static content = { 
groovy>   
groovy>         // name the search input control “field”, defining it with the jQuery like navigator 
groovy>         field { $("input", name: "q") } 
groovy>   
groovy>         // the search button declares that it takes us to the results page, and uses the  
groovy>         // parameterised buttonValue to define itself 
groovy>         button(to: GoogleResultsPage) {  
groovy>             $("input", value: buttonValue) 
groovy>         } 
groovy>     } 
groovy> } 
groovy>   
groovy> class GoogleHomePage extends Page { 
groovy>   
groovy>     // pages can define their location, either absolutely or relative to a base 
groovy>     static url = "http://google.com/ncr" 
groovy>   
groovy>     // “at checkers” allow verifying that the browser is at the expected page 
groovy>     static at = { title == "Google" } 
groovy>   
groovy>     static content = { 
groovy>         // include the previously defined module 
groovy>         search { module GoogleSearchModule, buttonValue: "Google Search" } 
groovy>     } 
groovy> } 
groovy>   
groovy> class GoogleResultsPage extends Page { 
groovy>     static at = { title.endsWith "Google Search" } 
groovy>     static content = { 
groovy>         // reuse our previously defined module 
groovy>         search { module GoogleSearchModule, buttonValue: "Search" } 
groovy>   
groovy>         // content definitions can compose and build from other definitions 
groovy>         results { $("li.g") } 
groovy>         result { i -> results[i] } 
groovy>         resultLink { i -> result(i).find("a.l") } 
groovy>         firstResultLink { resultLink(0) } 
groovy>     } 
groovy> } 
groovy>   
groovy> class WikipediaPage extends Page { 
groovy>     static at = { title == "Wikipedia" } 
groovy> } 
groovy> Browser.drive { 
groovy>     to GoogleHomePage 
groovy>     assert at(GoogleHomePage) 
groovy>     search.field.value("wikipedia") 
groovy>     waitFor { at GoogleResultsPage } 
groovy>     assert firstResultLink.text() == "Wikipedia" 
groovy>     firstResultLink.click() 
groovy>     waitFor { at WikipediaPage } 
groovy> } 
 
Exception thrown

groovy.lang.MissingPropertyException: No such property: firstResultLink for class: geb-exemple-maual-02

	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:51)

	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)

	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:304)

	at geb-exemple-maual-02$_run_closure1.doCall(geb-exemple-maual-02.groovy:68)

	at geb-exemple-maual-02$_run_closure1.doCall(geb-exemple-maual-02.groovy)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:606)

	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)

	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)

	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)

	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)

	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)

	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)

	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)

	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:114)

	at geb.Browser.drive(Browser.groovy:884)

	at geb.Browser$drive$0.callStatic(Unknown Source)

	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)

	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:191)

	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:211)

	at geb.Browser.drive(Browser.groovy:854)

	at geb.Browser$drive.call(Unknown Source)

	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)

	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)

	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:122)

	at geb-exemple-maual-02.run(geb-exemple-maual-02.groovy:63)

	at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:261)

	at groovy.lang.GroovyShell.run(GroovyShell.java:522)

	at groovy.lang.GroovyShell.run(GroovyShell.java:501)

	at groovy.lang.GroovyShell.run(GroovyShell.java:168)

	at groovy.lang.GroovyShell$run$0.call(Unknown Source)

	at groovy.ui.Console$_runScriptImpl_closure17.doCall(Console.groovy:977)

	at groovy.ui.Console$_runScriptImpl_closure17.doCall(Console.groovy)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:606)

	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)

	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)

	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)

	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)

	at groovy.lang.Closure.call(Closure.java:423)

	at groovy.lang.Closure.call(Closure.java:417)

	at groovy.lang.Closure.run(Closure.java:504)

	at java.lang.Thread.run(Thread.java:745)

**Comment by pepllubc** [comment]
the example code don't works  
this  work better
/*

*/
 @Grapes([ 
 @Grab("org.gebish:geb-core:0.9.2"), 
 //@Grab("org.gebish:geb-core:0.10.0"), 
 @Grab("org.seleniumhq.selenium:selenium-firefox-driver:2.45.0"), 
 @Grab("org.seleniumhq.selenium:selenium-support:2.45.0") 
 ]) 
 
 import geb.Browser 
 import geb.Page 
 import geb.Module 


 // modules are reusable fragments that can be used across pages that can be parameterised 
 // here we are using a module to model the search function on the home and results pages 
 class GoogleSearchModule extends Module { 
   // a parameterised value set when the module is included 
   def buttonValue 
 // the content DSL 
   static content = { 
     // name the search input control “field”, defining it with the jQuery like navigator 
     field { $("input", name: "q") } 
     // the search button declares that it takes us to the results page, and uses the
     // parameterised buttonValue to define itself 
     button(to: GoogleResultsPage) 
       {
          $("input", value: buttonValue) 
       } 
   } 
} 


 class GoogleHomePage extends Page { 
   // pages can define their location, either absolutely or relative to a base 
   static url = "http://google.com/ncr" 
   // “at checkers” allow verifying that the browser is at the expected page 
   static at = { title == "Google" } 
   static content = { 
       // include the previously defined module 
       search { module GoogleSearchModule, buttonValue: "Google Search" } 
     } 
 } 
 class GoogleResultsPage extends Page { 
 static at = { title.endsWith "Google Search" } 
 static content = { 
 // reuse our previously defined module 
 search { module GoogleSearchModule, buttonValue: "Search" } 


 // content definitions can compose and build from other definitions 
 results { $("li.g").find("h3") }   /*change 1*/
 result { i -> results[i] } 
 resultLink { i -> result(i).find("a") }  /*change2*/
 firstResultLink { resultLink(0) } 
 } 
 } 


 class WikipediaPage extends Page { 
 static at = { title == "Wikipedia" } 
 } 
 Browser.drive { 
 to GoogleHomePage 
 assert at(GoogleHomePage) 
 search.field.value("wikipedia") 
 waitFor { at GoogleResultsPage } 
 assert firstResultLink.text() == "Wikipedia" 
 firstResultLink.click() 
 waitFor { at WikipediaPage } 
 }

**Comment by pepllubc** [comment]
Now works
