### ISSUE TITLE
Setting non-multiple select field to null causes misleading error

### ISSUE THREAD

**Issue by mahileeb** [geb/issues#477]
{code}
java.lang.UnsupportedOperationException: You may only deselect all options of a multi-select

	at org.openqa.selenium.support.ui.Select.deselectAll(Select.java:219)
	at geb.navigator.NonEmptyNavigator.setSelectValue(NonEmptyNavigator.groovy:723)
	at geb.navigator.NonEmptyNavigator.setInputValue(NonEmptyNavigator.groovy:689)
	at geb.navigator.NonEmptyNavigator.setInputValues_closure40(NonEmptyNavigator.groovy:680)
	at groovy.lang.Closure.call(Closure.java:426)
	at geb.navigator.NonEmptyNavigator.setInputValues(NonEmptyNavigator.groovy:679)
	at geb.navigator.NonEmptyNavigator.propertyMissing(NonEmptyNavigator.groovy:593)
{code}

**Comment by mahileeb** [comment]
https://github.com/geb/geb/pull/128
