### ISSUE TITLE
Remote driver setup seems not to work

### ISSUE THREAD

**Issue by duc-gp** [geb/issues#556]
Hello,

i'm not sure if this is really a geb or a selenium bug, or maybe I'm using it completely wrong. Hope you can provide some information. I try to start tests with remote driver.

**prerequisite**
I've cloned the geb-example-gradle repository and made 2 changes to enable remote driver (according to docs http://www.gebish.org/manual/current/#factory-closure):
https://github.com/duc-talentwunder/geb-example-gradle/commit/888723fd834434c720ae6ad70ffb1c105182634a
https://github.com/duc-talentwunder/geb-example-gradle/commit/aa15c2fbbe051aec50fd25430a4ba6d1d996f711

then I used the following docker container by running:
docker run -d -p 4444:4444 -p 5900:5900 -v /dev/shm:/dev/shm selenium/standalone-chrome-debug:3.141.59-dubnium

taken from here: https://github.com/SeleniumHQ/docker-selenium

**when I run following command**
`./gradlew driverTest --tests GebishOrgSpec`

**I expect the test runs through successfully**

**Instead I get errors**
`GebishOrgSpec > can get to the current Book of Geb FAILED
    geb.driver.DriverCreationException: failed to create driver from callback 'script1545227369192638596830$_run_closure2$_closure6$_closure10@7abab70'
        at geb.driver.CallbackDriverFactory.getDriver(CallbackDriverFactory.groovy:35)
        at geb.driver.CachingDriverFactory.getDriver_closure3(CachingDriverFactory.groovy:85)
        at geb.driver.CachingDriverFactory.getDriver_closure3(CachingDriverFactory.groovy)
        at geb.driver.CachingDriverFactory$SimpleCache.get(CachingDriverFactory.groovy:32)
        at geb.driver.CachingDriverFactory.getDriver(CachingDriverFactory.groovy:84)
        at geb.Configuration.createDriver(Configuration.groovy:374)
        at geb.Configuration.getDriver(Configuration.groovy:363)
        at geb.Browser.getDriver(Browser.groovy:119)
        at geb.navigator.factory.BrowserBackedNavigatorFactory.<init>(BrowserBackedNavigatorFactory.groovy:35)
        at geb.Configuration.createNavigatorFactory(Configuration.groovy:427)
        at geb.Browser.createNavigatorFactory(Browser.groovy:141)
        at geb.Browser.getNavigatorFactory(Browser.groovy:129)
        at geb.Page.init(Page.groovy:144)
        at geb.Browser.createPage(Browser.groovy:908)
        at geb.Browser.to(Browser.groovy:588)
        at geb.Browser.to(Browser.groovy:577)
        at geb.spock.GebSpec.methodMissing(GebSpec.groovy:60)
        at GebishOrgSpec.can get to the current Book of Geb(GebishOrgSpec.groovy:7)

        Caused by:
        org.openqa.selenium.WebDriverException: Unable to parse remote response: <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <link rel="stylesheet" type="text/css" href="/assets/displayhelpservlet.css" media="all"/>
          <link href="/assets/favicon.ico" rel="icon" type="image/x-icon" />
          <script src="/assets/jquery-3.1.1.min.js" type="text/javascript"></script>
          <script src="/assets/displayhelpservlet.js" type="text/javascript"></script>
          <script type="text/javascript">
            var json = Object.freeze('{"consoleLink": "\u002fwd\u002fhub","type": "Standalone","class": "org.openqa.grid.web.servlet.DisplayHelpHandler$DisplayHelpServletConfig","version": "3.141.59"}');
          </script>
        </head>
        <body>

        <div id="content">
          <div id="help-heading">
            <h1><span id="logo"></span></h1>
            <h2>Selenium <span class="se-type"></span>&nbsp;v.<span class="se-version"></span></h2>
          </div>

          <div id="content-body">
            <p>
              Whoops! The URL specified routes to this help page.
            </p>
            <p>
              For more information about Selenium <span class="se-type"></span> please see the
              <a class="se-docs">docs</a> and/or visit the <a class="se-wiki">wiki</a>.
              <span id="console-item">
                Or perhaps you are looking for the Selenium <span class="se-type"></span> <a class="se-console">console</a>.
              </span>
            </p>
            <p>
              Happy Testing!
            </p>
          </div>

          <div>
            <footer id="help-footer">
              Selenium is made possible through the efforts of our open source community, contributions from
              these <a href="https://github.com/SeleniumHQ/selenium/blob/master/AUTHORS">people</a>, and our
              <a href="http://www.seleniumhq.org/sponsors/">sponsors</a>.
           </footer>
          </div>
         </div>

        </body>
        </html>
        Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
        System info: host: 'tw-nb-042.intern', ip: '192.168.1.196', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14', java.version: '1.8.0_192'
        Driver info: driver.version: RemoteWebDriver
            at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:347)
            at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:136)
            at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
            at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
            at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:217)
            at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:140)
            at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)
            at script1545227369192638596830$_run_closure2.closure6$_closure10(script1545227369192638596830.groovy:47)
            at script1545227369192638596830$_run_closure2.closure6$_closure10(script1545227369192638596830.groovy)
            at geb.driver.CallbackDriverFactory.getDriver(CallbackDriverFactory.groovy:29)
            ... 17 more

    geb.driver.DriverCreationException: failed to create driver from callback 'script1545227369192638596830$_run_closure2$_closure6$_closure10@7abab70'

        Caused by:
        org.openqa.selenium.WebDriverException: Unable to parse remote response: <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <link rel="stylesheet" type="text/css" href="/assets/displayhelpservlet.css" media="all"/>
          <link href="/assets/favicon.ico" rel="icon" type="image/x-icon" />
          <script src="/assets/jquery-3.1.1.min.js" type="text/javascript"></script>
          <script src="/assets/displayhelpservlet.js" type="text/javascript"></script>
          <script type="text/javascript">
            var json = Object.freeze('{"consoleLink": "\u002fwd\u002fhub","type": "Standalone","class": "org.openqa.grid.web.servlet.DisplayHelpHandler$DisplayHelpServletConfig","version": "3.141.59"}');
          </script>
        </head>
        <body>

        <div id="content">
          <div id="help-heading">
            <h1><span id="logo"></span></h1>
            <h2>Selenium <span class="se-type"></span>&nbsp;v.<span class="se-version"></span></h2>
          </div>

          <div id="content-body">
            <p>
              Whoops! The URL specified routes to this help page.
            </p>
            <p>
              For more information about Selenium <span class="se-type"></span> please see the
              <a class="se-docs">docs</a> and/or visit the <a class="se-wiki">wiki</a>.
              <span id="console-item">
                Or perhaps you are looking for the Selenium <span class="se-type"></span> <a class="se-console">console</a>.
              </span>
            </p>
            <p>
              Happy Testing!
            </p>
          </div>

          <div>
            <footer id="help-footer">
              Selenium is made possible through the efforts of our open source community, contributions from
              these <a href="https://github.com/SeleniumHQ/selenium/blob/master/AUTHORS">people</a>, and our
              <a href="http://www.seleniumhq.org/sponsors/">sponsors</a>.
           </footer>
          </div>
         </div>

        </body>
        </html>
        Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
        System info: host: 'tw-nb-042.intern', ip: '192.168.1.196', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14', java.version: '1.8.0_192'
        Driver info: driver.version: RemoteWebDriver

1 test completed, 1 failed

> Task :driverTest FAILED

FAILURE: Build failed with an exception.`

**Comment by duc-gp** [comment]
my fault, needed to use
`http://localhost:4444/wd/hub` instead of only `http://localhost:4444` hope this helps to anybody else didnt know this before
