### ISSUE TITLE
groovy.lang.MissingMethodException: No signature of method: geb.navigator.NonEmptyNavigator.toQueryPage()

### ISSUE THREAD

**Issue by sgckh** [geb/issues#561]
i defined a method  in a Geb.Page subclass ，and invoke the method in geb closure.
most of time it works fine，but a few times it throws groovy.lang.MissingMethodException: No signature of method: geb.navigator.NonEmptyNavigator.toQueryPage().  the exception Increasing frequency  when new more than 10 browse instances  ,Concurrent execute 10+ thread

why this exception happened and why my method belongs to NonEmptyNavigator not the Page？

thanks a lot

import geb.Page
import groovy.util.logging.Slf4j
import org.openqa.selenium.By
/**
 * @Author: chukh
 * @Description:操作选项页面
 * @Date: Created in 11:10 2018/11/18
 */
@Slf4j
class IndexCenter extends Page {

    static url = 'http://example/123/index.html'

    static content = {
        终端 { $('#partnerCode') }
    }

    def toQueryPage() {
        waitFor("queryPermission") {
            $("div", data: "quotation_search").hasNot(By.className("permissions"))
        }
        log.info '拥有报价查询权限'
    }
}
-----------------------------------------------------
class Test1 extends TestNG {
    @Test
    void test2() {
        def browser = new Browser()
        browser.drive {
            to (IndexCenter)
            toQueryPage()
        }
    }
}

------------------------------------------------------
groovy.lang.MissingMethodException: No signature of method: geb.navigator.NonEmptyNavigator.toQueryPage() is applicable for argument types: () values: []
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:266)
	at geb.navigator.NonEmptyNavigator.methodMissing(NonEmptyNavigator.groovy:568)
	at sun.reflect.GeneratedMethodAccessor699.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1235)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1124)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:151)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:41)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
	at geb.content.PageContentSupport.methodMissing(PageContentSupport.groovy:35)
	at geb.content.PageContentSupport$methodMissing$0.call(Unknown Source)
	at geb.Page.methodMissing(Page.groovy:112)
	at sun.reflect.GeneratedMethodAccessor696.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:958)
	at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1289)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1237)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1018)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1001)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:182)
	at geb.Browser.methodMissing(Browser.groovy:217)
	at sun.reflect.GeneratedMethodAccessor383.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:958)
	at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1289)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1237)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:821)
	at geb.Browser.invokeMethod(Browser.groovy)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:414)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:338)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:237)
	at com.ch..........flow.Constants$__clinit__closure9.doCall(Constants.groovy:315)
	at sun.reflect.GeneratedMethodAccessor568.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1018)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1001)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:182)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeClosure(ScriptBytecodeAdapter.java:588)
	at com.chech-------uk.flow.step.pageStep.GebScriptExecutor.run(GebScriptExecutor.groovy:19)
	at com.ch.........stants$__clinit__closure1.doCall(Constants.groovy:31)
	at sun.reflect.GeneratedMethodAccessor329.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1109)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:421)
	at com............n.flow.Constants$__clinit__closure1.doCall(Constants.groovy:33)
	at sun.reflect.GeneratedMethodAccessor329.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1109)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:421)
	at com.................low.Constants$__clinit__closure1.doCall(Constants.groovy:33)
	at sun.reflect.GeneratedMethodAccessor329.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1109)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:421)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:237)
	at com.]]]]]]]]mmon.flow.ALoopFlow$_run_closure1.doCall(ALoopFlow.groovy:48)
	at sun.reflect.GeneratedMethodAccessor462.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:421)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.inject(DefaultGroovyMethods.java:6083)
	at org.codehaus.groovy.runtime.dgm$390.doMethodInvoke(Unknown Source)
	at com.ch========flow.ALoopFlow.run(ALoopFlow.groovy:35)
	at com.c.../////mmon.flow.Flow.run(Flow.groovy:25)
	at com.chec=========ow.Constants$__clinit__closure1.doCall(Constants.groovy:31)
	at sun.reflect.GeneratedMethodAccessor329.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1109)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:421)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:237)
	at com.cco65.flow.core.service.TSimpleService$Trait$Helper.service(TSimpleService.groovy:29)
	at com.chech.cpicrvice.GetPolicyService.service(GetPolicyService.groovy)
	at com.chervice.GetPolicyService.getHistoryPolicy(GetPolicyService.groovy:47)
	at com.cser.ms.controller.ThirdPartyPolicyResource$AsyncPolicyHandler.run(ThirdPartyPolicyResource.groovy:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by erdi** [comment]
I don't fully understand your setup - you say you are running your code concurrently but there isn't anything in the snippets you provided that would confirm it. Can you please clarify what you mean by:

>the exception Increasing frequency when new more than 10 browse instances ,Concurrent execute 10+ thread

Are you using a single instance of `Browser` class from multiple threads?

Also, what does `GebScriptExecutor.run()` do? It's in the stacktrace you provided but not in any of the snippets.

**Comment by erdi** [comment]
Closing due to no response from the original reporter.
