### ISSUE TITLE
Content definition called 'container' causes PageInstanceNotInitializedException

### ISSUE THREAD

**Issue by britter** [geb/issues#640]
When using Geb 5 Milestone 1 with Groovy 3.0.7 and Spock 2.0-M5-groovy-3.0 a content defintion
that is called "container" will cause a `PageInstanceNotInitializedException`. Take for example
the [Scripting with Page Objects](https://gebish.org/manual/current/#scripting-with-page-objects)
example from the documentation and change it like the following:

```groovy
class GebHomePage extends Page {
    static url = "http://gebish.org"

    static at = { title == "Geb - Very Groovy Browser Automation" }

    static content = {
        // having a content definition called container makes the test fail
//        manualsMenu { module(ManualsMenuModule) }
        container { module(ManualsMenuModule) }
    }
}
```

Using that in a simple `GebSpec` like this one will cause the error:

```groovy
class SimpleSpec extends GebSpec {

    def "go to page"() {
        expect:
        to GebHomePage
    }
}
```

Stacktrace:

```
Condition failed with Exception:

to GebHomePage
|  |
|  class com.example.GebHomePage
geb.error.PageInstanceNotInitializedException: Instance of page class com.example.GebHomePage has not been initialized. Please pass it to Browser.to(), Browser.via(), Browser.page() or Browser.at() before using it.
	at geb.Page.uninitializedException(Page.groovy:381)
	at geb.content.UninitializedPageContentSupport.getContent(UninitializedPageContentSupport.groovy:30)
	at geb.content.PageContentSupport.methodMissing(PageContentSupport.groovy:33)
	at geb.Page.methodMissing(Page.groovy:110)
	at groovy.lang.GroovyObject.invokeMethod(GroovyObject.java:39)
	at com.example.GebHomePage._clinit__closure2(MyPage.groovy:25)
	at geb.content.PageContentTemplateBuilder.build(PageContentTemplateBuilder.groovy:39)
	at geb.content.PageContentTemplateBuilder.build(PageContentTemplateBuilder.groovy:71)
	at geb.Page.init(Page.groovy:141)
	at geb.Browser.initialisePage(Browser.groovy:1140)
	at geb.Browser.createPage(Browser.groovy:824)
	at geb.Browser.to(Browser.groovy:532)
	at geb.Browser.to(Browser.groovy:521)
	at geb.spock.GebSpec.methodMissing(GebSpec.groovy:1)
	at com.example.SimpleSpec.go to page(SimpleSpec.groovy:9)
```

Reproducer project: https://github.com/britter/gradle-sandbox/tree/34c2c5ca10ad9ddccf75fdbc8a58341ad8caae54/geb-container-issue (you need to change the test task configuration to look up the chrome driver from the correct location on your system)

Build scan: https://scans.gradle.com/s/4y3u5237jzy3e/tests/:test/com.example.SimpleSpec/go%20to%20page#1

**Comment by erdi** [comment]
Thanks for reporting, @britter, I will take a look at this first thing tomorrow morning.

**Comment by britter** [comment]
@erdi thanks for looking into this so quickly!

**Comment by erdi** [comment]
[Another milestone is ready](https://search.maven.org/artifact/org.gebish/geb-core/5.0-milestone-2/jar) so that you can test it.

**Comment by erdi** [comment]
The mention above should be disregarded - I made a typo in the issue number when adding an issue to the Testcontainers project.
