### ISSUE TITLE
Can't find compatible version of Groovy?

### ISSUE THREAD

**Issue by bitsnaps** [geb/issues#690]
Hi,

When I was trying to find the min/max compatible version of groovy in my local environnement (I've already installed: `2.5.6`, `3.0.9`), I kept getting the following error:
```bash
➜  hello groovy demo.groovy  # Geb:7.0        
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during conversion: Conflicting module versions. Module [groovy-xml is loaded in version 3.0.9 and you are trying to load version 4.0.5...
➜  hello groovy demo.groovy # Geb 5.1
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during conversion: Conflicting module versions. Module [groovy-xml is loaded in version 3.0.9 and you are trying to load version 3.0.8 ...

➜  hello groovy demo.groovy # Geb:4.1
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during conversion: Conflicting module versions. Module [groovy-xml is loaded in version 3.0.9 and you are trying to load version 2.5.14 ...
```
Even when installing Groovy 4.0.5 I get this error:
```
Caught: java.lang.NoClassDefFoundError: com/google/common/net/UrlEscapers
java.lang.NoClassDefFoundError: com/google/common/net/UrlEscapers
	at geb.Browser.calculateUri(Browser.groovy:1101)
	at geb.Browser.go(Browser.groovy:506)
	at geb.Browser$go$0.callCurrent(Unknown Source)
	at geb.Browser.go(Browser.groovy:485)
	at demo$_run_closure1.doCall(demo.groovy:7)
	at demo$_run_closure1.doCall(demo.groovy)
	at geb.Browser.drive(Browser.groovy:134)
	at geb.Browser$drive.callStatic(Unknown Source)
	at geb.Browser.drive(Browser.groovy:104)
	at demo.run(demo.groovy:6)
Caused by: java.lang.ClassNotFoundException: com.google.common.net.UrlEscapers
```
I'm using JDK 11 and everything works fine in the groovy's ecosystem (grails, ratpack...)
Does Geb requires a specific version of groovy ?

**Comment by bitsnaps** [comment]
I end up back to Groovy 2.5.6 for the demo in the Geb's docs, with the following working versions:
```
@Grapes([
    @Grab(group='org.gebish', module='geb-core', version='3.4.1'),
    @Grab(group='org.seleniumhq.selenium', module='selenium-firefox-driver', version='3.141.59'),
    @Grab(group='org.seleniumhq.selenium', module='selenium-support', version='3.141.59')
])
```
